Exp with notes collection
alhaamid/todo-angular pull request #5
Opened 2018-06-08 11:34 UTC by alhaamid

A lot of changes. In short, you can add notes and todos that are coupled with your account only. 
Try for yourself to check out the changes. @abdulbeard

2018-06-13 14:09 UTC, abdulbeard commented on src/app/views/dashboard/dashboard.component.html
> +<div *ngIf="this.ns.allNotes" class="yourNotesSection" style="text-align:left" [@note]="this.ns.allNotes.length">
put all styles in the class, instead of using class and style both

2018-06-13 14:11 UTC, abdulbeard requested changes
Left one comment. Tis a small thing

2018-06-14 16:06 UTC, alhaamid commented
Done.

2018-06-14 20:18 UTC, abdulbeard approved these changes

2018-06-14 20:20 UTC, abdulbeard approved these changes

2018-06-14 20:20 UTC, merged